package com.itinna.smalltool.dao.model;

import java.util.Date;

public class Attachment extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.attachment_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long attachmentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long valueId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long attachementTypeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.url
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column attachment.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.attachment_id
     *
     * @return the value of attachment.attachment_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.attachment_id
     *
     * @param attachmentId
     *            the value for attachment.attachment_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * @return the valueId
     */
    public Long getValueId() {
        return valueId;
    }

    /**
     * @param valueId
     *            the valueId to set
     */
    public void setValueId(Long valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.attachement_type_id
     *
     * @return the value of attachment.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getAttachementTypeId() {
        return attachementTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.attachement_type_id
     *
     * @param attachementTypeId
     *            the value for attachment.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setAttachementTypeId(Long attachementTypeId) {
        this.attachementTypeId = attachementTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.url
     *
     * @return the value of attachment.url
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.url
     *
     * @param url
     *            the value for attachment.url
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.creator
     *
     * @return the value of attachment.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.creator
     *
     * @param creator
     *            the value for attachment.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.create_time
     *
     * @return the value of attachment.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.create_time
     *
     * @param createTime
     *            the value for attachment.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.modifier
     *
     * @return the value of attachment.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.modifier
     *
     * @param modifier
     *            the value for attachment.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column attachment.modify_time
     *
     * @return the value of attachment.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column attachment.modify_time
     *
     * @param modifyTime
     *            the value for attachment.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}