package com.itinna.smalltool.dao.model;

import java.util.Date;

public class AttachmentType extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long attachementTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.attachment_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String attachmentTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.attachement_type_id
     *
     * @return the value of attachment_type.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getAttachementTypeId() {
        return attachementTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.attachement_type_id
     *
     * @param attachementTypeId the value for attachment_type.attachement_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setAttachementTypeId(Long attachementTypeId) {
        this.attachementTypeId = attachementTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.attachment_type_name
     *
     * @return the value of attachment_type.attachment_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getAttachmentTypeName() {
        return attachmentTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.attachment_type_name
     *
     * @param attachmentTypeName the value for attachment_type.attachment_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setAttachmentTypeName(String attachmentTypeName) {
        this.attachmentTypeName = attachmentTypeName == null ? null : attachmentTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.desc
     *
     * @return the value of attachment_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.desc
     *
     * @param desc the value for attachment_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.creator
     *
     * @return the value of attachment_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.creator
     *
     * @param creator the value for attachment_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.create_time
     *
     * @return the value of attachment_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.create_time
     *
     * @param createTime the value for attachment_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.modifier
     *
     * @return the value of attachment_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.modifier
     *
     * @param modifier the value for attachment_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_type.modify_time
     *
     * @return the value of attachment_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_type.modify_time
     *
     * @param modifyTime the value for attachment_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}