package com.itinna.smalltool.dao.model;

import java.util.Date;

public class Configuration extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.group_key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String groupKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.id
     *
     * @return the value of configuration.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.id
     *
     * @param id the value for configuration.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.key
     *
     * @return the value of configuration.key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.key
     *
     * @param key the value for configuration.key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.value
     *
     * @return the value of configuration.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.value
     *
     * @param value the value for configuration.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.description
     *
     * @return the value of configuration.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.description
     *
     * @param description the value for configuration.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.group_key
     *
     * @return the value of configuration.group_key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getGroupKey() {
        return groupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.group_key
     *
     * @param groupKey the value for configuration.group_key
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setGroupKey(String groupKey) {
        this.groupKey = groupKey == null ? null : groupKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.creator
     *
     * @return the value of configuration.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.creator
     *
     * @param creator the value for configuration.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.create_time
     *
     * @return the value of configuration.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.create_time
     *
     * @param createTime the value for configuration.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.modifier
     *
     * @return the value of configuration.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.modifier
     *
     * @param modifier the value for configuration.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.modify_time
     *
     * @return the value of configuration.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.modify_time
     *
     * @param modifyTime the value for configuration.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}