package com.itinna.smalltool.dao.model;

import java.util.Date;

public class Configuration extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.config_id
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private Long configId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.config_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.config_value
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.desc
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.group_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private String groupKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.creator
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.create_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.modifier
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column configuration.modify_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.config_id
     *
     * @return the value of configuration.config_id
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public Long getConfigId() {
        return configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.config_id
     *
     * @param configId the value for configuration.config_id
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setConfigId(Long configId) {
        this.configId = configId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.config_key
     *
     * @return the value of configuration.config_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.config_key
     *
     * @param configKey the value for configuration.config_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.config_value
     *
     * @return the value of configuration.config_value
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.config_value
     *
     * @param configValue the value for configuration.config_value
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.desc
     *
     * @return the value of configuration.desc
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.desc
     *
     * @param desc the value for configuration.desc
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.group_key
     *
     * @return the value of configuration.group_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public String getGroupKey() {
        return groupKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.group_key
     *
     * @param groupKey the value for configuration.group_key
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setGroupKey(String groupKey) {
        this.groupKey = groupKey == null ? null : groupKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.creator
     *
     * @return the value of configuration.creator
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.creator
     *
     * @param creator the value for configuration.creator
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.create_time
     *
     * @return the value of configuration.create_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.create_time
     *
     * @param createTime the value for configuration.create_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.modifier
     *
     * @return the value of configuration.modifier
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.modifier
     *
     * @param modifier the value for configuration.modifier
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column configuration.modify_time
     *
     * @return the value of configuration.modify_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column configuration.modify_time
     *
     * @param modifyTime the value for configuration.modify_time
     *
     * @mbggenerated Thu Apr 06 12:54:57 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}