package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class Node extends BaseEntity {

    private List<Node> subNodes;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Integer nodeTypeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String isRequired;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String hasAttachment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column node.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column node.id
     *
     * @return the value of node.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.id
     *
     * @param id
     *            the value for node.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.parent_id
     *
     * @return the value of node.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.parent_id
     *
     * @param parentId
     *            the value for node.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.template_id
     *
     * @return the value of node.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.template_id
     *
     * @param templateId
     *            the value for node.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.node_type_id
     *
     * @return the value of node.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Integer getNodeTypeId() {
        return nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.node_type_id
     *
     * @param nodeTypeId
     *            the value for node.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setNodeTypeId(Integer nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column node.name
     *
     * @return the value of node.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.name
     *
     * @param name
     *            the value for node.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.position
     *
     * @return the value of node.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.position
     *
     * @param position
     *            the value for node.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.is_required
     *
     * @return the value of node.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.is_required
     *
     * @param isRequired
     *            the value for node.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired == null ? null : isRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.has_attachment
     *
     * @return the value of node.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getHasAttachment() {
        return hasAttachment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.has_attachment
     *
     * @param hasAttachment
     *            the value for node.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setHasAttachment(String hasAttachment) {
        this.hasAttachment = hasAttachment == null ? null : hasAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column node.creator
     *
     * @return the value of node.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.creator
     *
     * @param creator
     *            the value for node.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.create_time
     *
     * @return the value of node.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.create_time
     *
     * @param createTime
     *            the value for node.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.modifier
     *
     * @return the value of node.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column node.modifier
     *
     * @param modifier
     *            the value for node.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * node.modify_time
     *
     * @return the value of node.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * node.modify_time
     *
     * @param modifyTime
     *            the value for node.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @return the subNodes
     */
    public List<Node> getSubNodes() {
        return subNodes;
    }

    /**
     * @param subNodes
     *            the subNodes to set
     */
    public void setSubNodes(List<Node> subNodes) {
        this.subNodes = subNodes;
    }
}