package com.itinna.smalltool.dao.model;

import java.util.Date;

public class NodeType extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long nodeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.node_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String nodeTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column node_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.node_type_id
     *
     * @return the value of node_type.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getNodeTypeId() {
        return nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.node_type_id
     *
     * @param nodeTypeId the value for node_type.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeTypeId(Long nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.node_type_name
     *
     * @return the value of node_type.node_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getNodeTypeName() {
        return nodeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.node_type_name
     *
     * @param nodeTypeName the value for node_type.node_type_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeTypeName(String nodeTypeName) {
        this.nodeTypeName = nodeTypeName == null ? null : nodeTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.desc
     *
     * @return the value of node_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.desc
     *
     * @param desc the value for node_type.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.creator
     *
     * @return the value of node_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.creator
     *
     * @param creator the value for node_type.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.create_time
     *
     * @return the value of node_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.create_time
     *
     * @param createTime the value for node_type.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.modifier
     *
     * @return the value of node_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.modifier
     *
     * @param modifier the value for node_type.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column node_type.modify_time
     *
     * @return the value of node_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column node_type.modify_time
     *
     * @param modifyTime the value for node_type.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}