package com.itinna.smalltool.dao.model;

import java.util.Date;

public class Node extends BaseEntity {

    private int position;

    /**
     * @return the position
     */
    public int getPosition() {
        return position;
    }

    /**
     * @param position
     *            the position to set
     */
    public void setPosition(int position) {
        this.position = position;
    }

    private NodeType nodeType;

    /**
     * @return the nodeType
     */
    public NodeType getNodeType() {
        return nodeType;
    }

    /**
     * @param nodeType
     *            the nodeType to set
     */
    public void setNodeType(NodeType nodeType) {
        this.nodeType = nodeType;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long nodeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.parent_node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long parentNodeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long nodeTypeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.node_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.is_required
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String isRequired;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column node.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.node_id
     *
     * @return the value of node.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.node_id
     *
     * @param nodeId
     *            the value for node.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.parent_node_id
     *
     * @return the value of node.parent_node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getParentNodeId() {
        return parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.parent_node_id
     *
     * @param parentNodeId
     *            the value for node.parent_node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setParentNodeId(Long parentNodeId) {
        this.parentNodeId = parentNodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.node_type_id
     *
     * @return the value of node.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getNodeTypeId() {
        return nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.node_type_id
     *
     * @param nodeTypeId
     *            the value for node.node_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeTypeId(Long nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.template_id
     *
     * @return the value of node.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.template_id
     *
     * @param templateId
     *            the value for node.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.node_name
     *
     * @return the value of node.node_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.node_name
     *
     * @param nodeName
     *            the value for node.node_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.is_required
     *
     * @return the value of node.is_required
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.is_required
     *
     * @param isRequired
     *            the value for node.is_required
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired == null ? null : isRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.creator
     *
     * @return the value of node.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.creator
     *
     * @param creator
     *            the value for node.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.create_time
     *
     * @return the value of node.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.create_time
     *
     * @param createTime
     *            the value for node.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.modifier
     *
     * @return the value of node.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.modifier
     *
     * @param modifier
     *            the value for node.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column node.modify_time
     *
     * @return the value of node.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column node.modify_time
     *
     * @param modifyTime
     *            the value for node.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}