package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class Report extends BaseEntity {

    private List<ReportValue> reportValues;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report.id
     *
     * @param id
     *            the value for report.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.user_id
     *
     * @return the value of report.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report.user_id
     *
     * @param userId
     *            the value for report.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.template_id
     *
     * @return the value of report.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report.template_id
     *
     * @param templateId
     *            the value for report.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column report.name
     *
     * @return the value of report.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report.name
     *
     * @param name
     *            the value for report.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.creator
     *
     * @return the value of report.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report.creator
     *
     * @param creator
     *            the value for report.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report.create_time
     *
     * @param createTime
     *            the value for report.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.modifier
     *
     * @return the value of report.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report.modifier
     *
     * @param modifier
     *            the value for report.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report.modify_time
     *
     * @return the value of report.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report.modify_time
     *
     * @param modifyTime
     *            the value for report.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @return the reportValues
     */
    public List<ReportValue> getReportValues() {
        return reportValues;
    }

    /**
     * @param reportValues
     *            the reportValues to set
     */
    public void setReportValues(List<ReportValue> reportValues) {
        this.reportValues = reportValues;
    }

}