package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class Report extends BaseEntity {

    private List<ReportNodeValue> nodeValues;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long reportId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.report_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.report_id
     *
     * @return the value of report.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.report_id
     *
     * @param reportId
     *            the value for report.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.template_id
     *
     * @return the value of report.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.template_id
     *
     * @param templateId
     *            the value for report.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.user_id
     *
     * @return the value of report.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.user_id
     *
     * @param userId
     *            the value for report.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.report_name
     *
     * @return the value of report.report_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.report_name
     *
     * @param reportName
     *            the value for report.report_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.creator
     *
     * @return the value of report.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.creator
     *
     * @param creator
     *            the value for report.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.create_time
     *
     * @return the value of report.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.create_time
     *
     * @param createTime
     *            the value for report.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.modifier
     *
     * @return the value of report.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.modifier
     *
     * @param modifier
     *            the value for report.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report.modify_time
     *
     * @return the value of report.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report.modify_time
     *
     * @param modifyTime
     *            the value for report.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @return the nodeValues
     */
    public List<ReportNodeValue> getNodeValues() {
        return nodeValues;
    }

    /**
     * @param nodeValues
     *            the nodeValues to set
     */
    public void setNodeValues(List<ReportNodeValue> nodeValues) {
        this.nodeValues = nodeValues;
    }
}