package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class ReportValue extends BaseEntity {

    private List<Attachment> attachments;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report_value.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.report_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Integer nodeTypeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report_value.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report_value.node_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String nodeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report_value.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Integer position;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String isRequired;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String hasAttachment;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column report_value.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * report_value.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.id
     *
     * @return the value of report_value.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column report_value.id
     *
     * @param id
     *            the value for report_value.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.report_id
     *
     * @return the value of report_value.report_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.report_id
     *
     * @param reportId
     *            the value for report_value.report_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setReportId(String reportId) {
        this.reportId = reportId == null ? null : reportId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.node_type_id
     *
     * @return the value of report_value.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Integer getNodeTypeId() {
        return nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.node_type_id
     *
     * @param nodeTypeId
     *            the value for report_value.node_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setNodeTypeId(Integer nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.value
     *
     * @return the value of report_value.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.value
     *
     * @param value
     *            the value for report_value.value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.node_id
     *
     * @return the value of report_value.node_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.node_id
     *
     * @param nodeId
     *            the value for report_value.node_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId == null ? null : nodeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.parent_id
     *
     * @return the value of report_value.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.parent_id
     *
     * @param parentId
     *            the value for report_value.parent_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.name
     *
     * @return the value of report_value.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.name
     *
     * @param name
     *            the value for report_value.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.position
     *
     * @return the value of report_value.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.position
     *
     * @param position
     *            the value for report_value.position
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.is_required
     *
     * @return the value of report_value.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.is_required
     *
     * @param isRequired
     *            the value for report_value.is_required
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setIsRequired(String isRequired) {
        this.isRequired = isRequired == null ? null : isRequired.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.has_attachment
     *
     * @return the value of report_value.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getHasAttachment() {
        return hasAttachment;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.has_attachment
     *
     * @param hasAttachment
     *            the value for report_value.has_attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setHasAttachment(String hasAttachment) {
        this.hasAttachment = hasAttachment == null ? null : hasAttachment.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.creator
     *
     * @return the value of report_value.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.creator
     *
     * @param creator
     *            the value for report_value.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.create_time
     *
     * @return the value of report_value.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.create_time
     *
     * @param createTime
     *            the value for report_value.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.modifier
     *
     * @return the value of report_value.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.modifier
     *
     * @param modifier
     *            the value for report_value.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * report_value.modify_time
     *
     * @return the value of report_value.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * report_value.modify_time
     *
     * @param modifyTime
     *            the value for report_value.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @return the attachments
     */
    public List<Attachment> getAttachments() {
        return attachments;
    }

    /**
     * @param attachments
     *            the attachments to set
     */
    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }
}