package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class ReportNodeValue extends BaseEntity {

    private List<Attachment> attachments;

    /**
     * @return the attachments
     */
    public List<Attachment> getAttachments() {
        return attachments;
    }

    /**
     * @param attachments
     *            the attachments to set
     */
    public void setAttachments(List<Attachment> attachments) {
        this.attachments = attachments;
    }

    private Node node;

    /**
     * @return the node
     */
    public Node getNode() {
        return node;
    }

    /**
     * @param node
     *            the node to set
     */
    public void setNode(Node node) {
        this.node = node;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.value_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long valueId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long reportId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long nodeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.value
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column report_node_value.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.value_id
     *
     * @return the value of report_node_value.value_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getValueId() {
        return valueId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.value_id
     *
     * @param valueId
     *            the value for report_node_value.value_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setValueId(Long valueId) {
        this.valueId = valueId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.report_id
     *
     * @return the value of report_node_value.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.report_id
     *
     * @param reportId
     *            the value for report_node_value.report_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.node_id
     *
     * @return the value of report_node_value.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.node_id
     *
     * @param nodeId
     *            the value for report_node_value.node_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.value
     *
     * @return the value of report_node_value.value
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.value
     *
     * @param value
     *            the value for report_node_value.value
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.creator
     *
     * @return the value of report_node_value.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.creator
     *
     * @param creator
     *            the value for report_node_value.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.create_time
     *
     * @return the value of report_node_value.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.create_time
     *
     * @param createTime
     *            the value for report_node_value.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.modifier
     *
     * @return the value of report_node_value.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.modifier
     *
     * @param modifier
     *            the value for report_node_value.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column report_node_value.modify_time
     *
     * @return the value of report_node_value.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column report_node_value.modify_time
     *
     * @param modifyTime
     *            the value for report_node_value.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}