package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class Template extends BaseEntity {

    private List<Node> nodes;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column template.id
     *
     * @param id
     *            the value for template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.name
     *
     * @return the value of template.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column template.name
     *
     * @param name
     *            the value for template.name
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.description
     *
     * @return the value of template.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * template.description
     *
     * @param description
     *            the value for template.description
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.creator
     *
     * @return the value of template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * template.creator
     *
     * @param creator
     *            the value for template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.create_time
     *
     * @return the value of template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * template.create_time
     *
     * @param createTime
     *            the value for template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.modifier
     *
     * @return the value of template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * template.modifier
     *
     * @param modifier
     *            the value for template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * template.modify_time
     *
     * @return the value of template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * template.modify_time
     *
     * @param modifyTime
     *            the value for template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * @return the nodes
     */
    public List<Node> getNodes() {
        return nodes;
    }

    /**
     * @param nodes
     *            the nodes to set
     */
    public void setNodes(List<Node> nodes) {
        this.nodes = nodes;
    }
}