package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class Template extends BaseEntity {

    private List<Node> nodes;

    /**
     * @return the nodes
     */
    public List<Node> getNodes() {
        return nodes;
    }

    /**
     * @param nodes
     *            the nodes to set
     */
    public void setNodes(List<Node> nodes) {
        this.nodes = nodes;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.template_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.template_id
     *
     * @return the value of template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.template_id
     *
     * @param templateId
     *            the value for template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.template_name
     *
     * @return the value of template.template_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.template_name
     *
     * @param templateName
     *            the value for template.template_name
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.desc
     *
     * @return the value of template.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.desc
     *
     * @param desc
     *            the value for template.desc
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.creator
     *
     * @return the value of template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.creator
     *
     * @param creator
     *            the value for template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.create_time
     *
     * @return the value of template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.create_time
     *
     * @param createTime
     *            the value for template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.modifier
     *
     * @return the value of template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.modifier
     *
     * @param modifier
     *            the value for template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column template.modify_time
     *
     * @return the value of template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column template.modify_time
     *
     * @param modifyTime
     *            the value for template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}