package com.itinna.smalltool.dao.model;

import java.util.Date;

public class User extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cellphone_no
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String cellphoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cellphone_no
     *
     * @return the value of user.cellphone_no
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCellphoneNo() {
        return cellphoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cellphone_no
     *
     * @param cellphoneNo the value for user.cellphone_no
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCellphoneNo(String cellphoneNo) {
        this.cellphoneNo = cellphoneNo == null ? null : cellphoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.creator
     *
     * @return the value of user.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.creator
     *
     * @param creator the value for user.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modifier
     *
     * @return the value of user.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modifier
     *
     * @param modifier the value for user.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modify_time
     *
     * @return the value of user.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modify_time
     *
     * @param modifyTime the value for user.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}