package com.itinna.smalltool.dao.model;

import java.util.Date;

public class UserTemplate extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String templateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.is_admin
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String isAdmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.id
     *
     * @return the value of user_template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.id
     *
     * @param id the value for user_template.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.user_id
     *
     * @return the value of user_template.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.user_id
     *
     * @param userId the value for user_template.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.template_id
     *
     * @return the value of user_template.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.template_id
     *
     * @param templateId the value for user_template.template_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.is_admin
     *
     * @return the value of user_template.is_admin
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.is_admin
     *
     * @param isAdmin the value for user_template.is_admin
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin == null ? null : isAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.creator
     *
     * @return the value of user_template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.creator
     *
     * @param creator the value for user_template.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.create_time
     *
     * @return the value of user_template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.create_time
     *
     * @param createTime the value for user_template.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.modifier
     *
     * @return the value of user_template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.modifier
     *
     * @param modifier the value for user_template.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_template.modify_time
     *
     * @return the value of user_template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_template.modify_time
     *
     * @param modifyTime the value for user_template.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}