package com.itinna.smalltool.dao.model;

import java.util.Date;
import java.util.List;

public class UserTemplate extends BaseEntity {

    private List<Template> templates;

    /**
     * @return the templates
     */
    public List<Template> getTemplates() {
        return templates;
    }

    /**
     * @param templates
     *            the templates to set
     */
    public void setTemplates(List<Template> templates) {
        this.templates = templates;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.user_template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long userTemplateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long templateId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.is_admin
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String isAdmin;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.user_template_id
     *
     * @return the value of user_template.user_template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getUserTemplateId() {
        return userTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.user_template_id
     *
     * @param userTemplateId
     *            the value for user_template.user_template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserTemplateId(Long userTemplateId) {
        this.userTemplateId = userTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.user_id
     *
     * @return the value of user_template.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.user_id
     *
     * @param userId
     *            the value for user_template.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.template_id
     *
     * @return the value of user_template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.template_id
     *
     * @param templateId
     *            the value for user_template.template_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.is_admin
     *
     * @return the value of user_template.is_admin
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getIsAdmin() {
        return isAdmin;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.is_admin
     *
     * @param isAdmin
     *            the value for user_template.is_admin
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin == null ? null : isAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.creator
     *
     * @return the value of user_template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.creator
     *
     * @param creator
     *            the value for user_template.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.create_time
     *
     * @return the value of user_template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.create_time
     *
     * @param createTime
     *            the value for user_template.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.modifier
     *
     * @return the value of user_template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.modifier
     *
     * @param modifier
     *            the value for user_template.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_template.modify_time
     *
     * @return the value of user_template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_template.modify_time
     *
     * @param modifyTime
     *            the value for user_template.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}