package com.itinna.smalltool.dao.model;

import java.util.Date;

public class UserApp extends BaseEntity {

    private AppType appType;

    private User user;

    /**
     * @return the user
     */
    public User getUser() {
        return user;
    }

    /**
     * @param user
     *            the user to set
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * @return the appType
     */
    public AppType getAppType() {
        return appType;
    }

    /**
     * @param appType
     *            the appType to set
     */
    public void setAppType(AppType appType) {
        this.appType = appType;
    }

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.user_app_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long userAppId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.app_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long appTypeId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.user_biz_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private String userBizId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Long modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user_app.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.user_app_id
     *
     * @return the value of user_app.user_app_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getUserAppId() {
        return userAppId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.user_app_id
     *
     * @param userAppId
     *            the value for user_app.user_app_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserAppId(Long userAppId) {
        this.userAppId = userAppId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.user_id
     *
     * @return the value of user_app.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.user_id
     *
     * @param userId
     *            the value for user_app.user_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.app_type_id
     *
     * @return the value of user_app.app_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getAppTypeId() {
        return appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.app_type_id
     *
     * @param appTypeId
     *            the value for user_app.app_type_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setAppTypeId(Long appTypeId) {
        this.appTypeId = appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.user_biz_id
     *
     * @return the value of user_app.user_biz_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public String getUserBizId() {
        return userBizId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.user_biz_id
     *
     * @param userBizId
     *            the value for user_app.user_biz_id
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setUserBizId(String userBizId) {
        this.userBizId = userBizId == null ? null : userBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.creator
     *
     * @return the value of user_app.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.creator
     *
     * @param creator
     *            the value for user_app.creator
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.create_time
     *
     * @return the value of user_app.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.create_time
     *
     * @param createTime
     *            the value for user_app.create_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.modifier
     *
     * @return the value of user_app.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Long getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.modifier
     *
     * @param modifier
     *            the value for user_app.modifier
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifier(Long modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user_app.modify_time
     *
     * @return the value of user_app.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user_app.modify_time
     *
     * @param modifyTime
     *            the value for user_app.modify_time
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}