package com.itinna.smalltool.dao.model;

import java.util.Date;

public class UserApp extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.app_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Integer appTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.app_user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String appUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_app.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.id
     *
     * @return the value of user_app.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.id
     *
     * @param id the value for user_app.id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.user_id
     *
     * @return the value of user_app.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.user_id
     *
     * @param userId the value for user_app.user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.app_type_id
     *
     * @return the value of user_app.app_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Integer getAppTypeId() {
        return appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.app_type_id
     *
     * @param appTypeId the value for user_app.app_type_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setAppTypeId(Integer appTypeId) {
        this.appTypeId = appTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.app_user_id
     *
     * @return the value of user_app.app_user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getAppUserId() {
        return appUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.app_user_id
     *
     * @param appUserId the value for user_app.app_user_id
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId == null ? null : appUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.creator
     *
     * @return the value of user_app.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.creator
     *
     * @param creator the value for user_app.creator
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.create_time
     *
     * @return the value of user_app.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.create_time
     *
     * @param createTime the value for user_app.create_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.modifier
     *
     * @return the value of user_app.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.modifier
     *
     * @param modifier the value for user_app.modifier
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_app.modify_time
     *
     * @return the value of user_app.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_app.modify_time
     *
     * @param modifyTime the value for user_app.modify_time
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}