package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.Attachment;

public interface AttachmentMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(Attachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    Attachment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(Attachment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table attachment
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(Attachment record);

    List<Attachment> selectByPeportValueId(String reportValueId);
}