package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.AttachmentType;

public interface AttachmentTypeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    AttachmentType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(AttachmentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(AttachmentType record);
}