package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.NodeType;

public interface NodeTypeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int deleteByPrimaryKey(Long nodeTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insert(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insertSelective(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    NodeType selectByPrimaryKey(Long nodeTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKeySelective(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKey(NodeType record);
}