package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.NodeType;

public interface NodeTypeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    NodeType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(NodeType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table node_type
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(NodeType record);
}