package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.ReportValue;

public interface ReportValueMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(ReportValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(ReportValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    ReportValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(ReportValue record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report_value
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(ReportValue record);

    List<ReportValue> selectByReportId(String reportId);

}