package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.Report;
import com.itinna.smalltool.web.form.SearchReportForm;

public interface ReportMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int deleteByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    Report selectByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table report
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKey(Report record);

    Report selectDetailByPrimaryKey(long reportId);

    List<Report> selectByCondition(SearchReportForm form);

    int countByCondition(SearchReportForm form);
}