package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.Report;

public interface ReportMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    Report selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table report
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(Report record);

    List<Report> selectByTemplateId(String templateId);

    List<Report> selectDetailByPrimaryKey(String reportId);
}