package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.Template;
import com.itinna.smalltool.web.form.report.SelectReportTypeForm;

public interface TemplateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int deleteByPrimaryKey(Long templateId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    Template selectByPrimaryKey(Long templateId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKey(Template record);

    /**
     * 计算某用户可填写的模版（报表类型）
     * 
     * @param userId
     * @return
     */
    int countWritableByUserId(long userId);

    /**
     * 查找某用户可填写的模版集合（可分页查找）
     * 
     * @param form
     * @return
     */
    List<Template> selectWritableByUserId(SelectReportTypeForm form);

    Template select4ReportCreatingByTemplateId(long templateId);
}