package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.Template;

public interface TemplateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    Template selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(Template record);

    Template selectDetailByPrimaryKey(String id);
}