package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.User;

public interface UserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    User selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table user
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKey(User record);

    /**
     * 查找管理员以及可管理的模版集合
     * 
     * @param userId
     * @return
     */
    User selectAdminWithTemplatesByUserId(long userId, int fromRecord, int pageSize);

    /**
     * 查找普通用户以及可填写的模版集合
     * 
     * @param userId
     * @return
     */
    User selectUserWithTemplatesByUserId(long userId, int fromRecord, int pageSize);

    /**
     * 查找用户及其某种类型的报表集合
     * 
     * @param userId
     * @param templateId
     * @param fromRecord
     * @param pageSize
     * @return
     */
    User selectUserWithReportsByUserId(long userId, Long templateId, int fromRecord, int pageSize);

    /**
     * 查找用户及其应用集合
     * 
     * @param userId
     * @return
     */
    User selectUserWithAppsByUserId(long userId, int fromRecord, int pageSize);
}