package com.itinna.smalltool.dao.mapper;

import com.itinna.smalltool.dao.model.UserTemplate;

public interface UserTemplateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int deleteByPrimaryKey(Long userTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insert(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int insertSelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    UserTemplate selectByPrimaryKey(Long userTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKeySelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_template
     *
     * @mbggenerated Tue Apr 04 19:01:32 CST 2017
     */
    int updateByPrimaryKey(UserTemplate record);
}