package com.itinna.smalltool.dao.mapper;

import java.util.List;

import com.itinna.smalltool.dao.model.UserTemplate;

public interface UserTemplateMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insert(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int insertSelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    UserTemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKeySelective(UserTemplate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_template
     *
     * @mbggenerated Fri Apr 21 15:31:37 CST 2017
     */
    int updateByPrimaryKey(UserTemplate record);

    List<UserTemplate> selectByTemplateId(String templateId);

    List<UserTemplate> selectByUserId(String userId);
}