-- MySQL Script generated by MySQL Workbench
-- Thu Apr 27 11:26:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biaojiang
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biaojiang
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biaojiang` DEFAULT CHARACTER SET utf8 ;
USE `biaojiang` ;

-- -----------------------------------------------------
-- Table `biaojiang`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`user` (
  `id` VARCHAR(36) NOT NULL,
  `cellphone` VARCHAR(20) NULL,
  `password` VARCHAR(20) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `cellphone_no_UNIQUE` (`cellphone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`app_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`app_type` (
  `id` INT NOT NULL COMMENT 'uuid',
  `type` VARCHAR(20) NOT NULL,
  `description` VARCHAR(50) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`user_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`user_app` (
  `id` VARCHAR(36) NOT NULL COMMENT 'uuid',
  `user_id` VARCHAR(36) NOT NULL,
  `app_type_id` INT NOT NULL,
  `app_user_id` VARCHAR(50) NOT NULL COMMENT '用户在授权app中的唯一标识',
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_app_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_app_app_type1_idx` (`app_type_id` ASC),
  CONSTRAINT `fk_user_app_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `biaojiang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_app_app_type1`
    FOREIGN KEY (`app_type_id`)
    REFERENCES `biaojiang`.`app_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`template` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(50) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`user_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`user_template` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `template_id` VARCHAR(36) NOT NULL,
  `is_admin` CHAR(1) NOT NULL DEFAULT 0 COMMENT '0：非管理员\n1：管理员',
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_template_user1_idx` (`user_id` ASC),
  INDEX `fk_user_template_template1_idx` (`template_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_user_template_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `biaojiang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_template_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `biaojiang`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`node_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`node_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `description` VARCHAR(50) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`node` (
  `id` VARCHAR(36) NOT NULL,
  `parent_id` VARCHAR(36) NOT NULL DEFAULT 0,
  `template_id` VARCHAR(36) NOT NULL,
  `node_type_id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `position` INT NOT NULL,
  `is_required` CHAR(1) NULL DEFAULT 0 COMMENT '0：选填项\n1：必填项',
  `has_attachment` CHAR(1) NULL DEFAULT 0 COMMENT '0:无附件\n1:有附件',
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_node_template1_idx` (`template_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_node_node_type1_idx` (`node_type_id` ASC),
  CONSTRAINT `fk_node_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `biaojiang`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_node_node_type1`
    FOREIGN KEY (`node_type_id`)
    REFERENCES `biaojiang`.`node_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`report` (
  `id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `template_id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_user1_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_report_template1_idx` (`template_id` ASC),
  CONSTRAINT `fk_report_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `biaojiang`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_template1`
    FOREIGN KEY (`template_id`)
    REFERENCES `biaojiang`.`template` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`report_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`report_value` (
  `id` VARCHAR(36) NOT NULL,
  `report_id` VARCHAR(36) NOT NULL,
  `node_type_id` INT NOT NULL,
  `value` VARCHAR(500) NULL,
  `node_id` VARCHAR(36) NOT NULL,
  `parent_id` VARCHAR(36) NULL DEFAULT 0,
  `name` VARCHAR(50) NOT NULL,
  `position` INT NOT NULL,
  `is_required` CHAR(1) NULL,
  `has_attachment` CHAR(1) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_report_value_report1_idx` (`report_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_report_value_node_type1_idx` (`node_type_id` ASC),
  CONSTRAINT `fk_report_value_report1`
    FOREIGN KEY (`report_id`)
    REFERENCES `biaojiang`.`report` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_report_value_node_type1`
    FOREIGN KEY (`node_type_id`)
    REFERENCES `biaojiang`.`node_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`attachment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`attachment_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `description` VARCHAR(50) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`attachment` (
  `id` VARCHAR(36) NOT NULL,
  `report_value_id` VARCHAR(36) NOT NULL,
  `attachment_type_id` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attachment_report_value1_idx` (`report_value_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_attachment_attachment_type1_idx` (`attachment_type_id` ASC),
  CONSTRAINT `fk_attachment_report_value1`
    FOREIGN KEY (`report_value_id`)
    REFERENCES `biaojiang`.`report_value` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attachment_attachment_type1`
    FOREIGN KEY (`attachment_type_id`)
    REFERENCES `biaojiang`.`attachment_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biaojiang`.`configuration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biaojiang`.`configuration` (
  `id` VARCHAR(3) NOT NULL COMMENT 'uuid',
  `key` VARCHAR(45) NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `group_key` VARCHAR(45) NULL,
  `creator` VARCHAR(36) NULL,
  `create_time` TIMESTAMP NULL,
  `modifier` VARCHAR(36) NULL,
  `modify_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `key_UNIQUE` (`key` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
